// =============================================
// TECHO CONNECT — PRODUCT DATA
// =============================================

export const mainProducts = [
  {
    id: 'yagi-pro',
    slug: 'yagi-pro',
    name: 'Yagi Pro',
    tagline: 'The Essential Signal Booster',
    description: `Our Yagi Pro antenna is specially designed to boost weak 4G and 4G+ LTE signals for wireless routers used across Sri Lanka. Ideal for areas with low signal strength, long distances from towers, or unstable internet connections. Features a 10M RG6 low-loss cable for flexible installation.`,
    badge: 'Fast Moving',
    badgeColor: '#0AAD6E',
    warranty: { checking: '5 Days', service: '6 Months' },
    features: [
      'Boosts 4G / 4G+ LTE signals',
      '10M RG6 low-loss cable included',
      'Universal SMA Male connector (Gold)',
      'Compatible with all Sri Lankan carriers',
      'Easy DIY installation',
      'Outdoor weatherproof design',
    ],
    compatible: ['Dialog 4G Router', 'Mobitel 4G Router', 'SLT 4G Router', 'Hutch 4G Router'],
    variants: [
      {
        id: 'yagi-pro-v1',
        name: '10M Wire + Antenna',
        includes: ['10M RG6 Cable', 'Yagi Antenna Assembly', 'SMA Male Connector (Gold)', 'Mounting Hardware'],
        price: 3600,
        image: '/products/yagi-pro-10m.webp',
        weight: 600,
        inStock: true,
      },
      {
        id: 'yagi-pro-v2',
        name: '10M Wire + Antenna + Dipole Weather Protection',
        includes: ['10M RG6 Cable', 'Yagi Antenna Assembly', 'SMA Male Connector (Gold)', 'Dipole Weather Protection Cover', 'Mounting Hardware'],
        price: 3800,
        weight: 610,
        inStock: true,
      },
      {
        id: 'yagi-pro-v3',
        name: '10M Wire + Antenna + Director Element Caps',
        includes: ['10M RG6 Cable', 'Yagi Antenna Assembly', 'SMA Male Connector (Gold)', 'Director Element Caps', 'Mounting Hardware'],
        price: 3800,
        weight: 620,
        inStock: true,
      },
      {
        id: 'yagi-pro-v4',
        name: '10M Wire + Antenna + Director Caps + Dipole Protection',
        includes: ['10M RG6 Cable', 'Yagi Antenna Assembly', 'SMA Male Connector (Gold)', 'Director Element Caps', 'Dipole Weather Protection Cover', 'Mounting Hardware'],
        price: 3900,
        weight: 630,
        inStock: true,
      },
    ],
    images: ['/products/yagi-pro-1.png','/products/yagi-pro-10m.webp'],
    specs: {
      'Cable Length': '10 Metres',
      'Connector Type': 'SMA Male (Gold Plated)',
      'Cable Type': 'RG6 Low-Loss',
      'Frequency': '700MHz – 2700MHz',
      'Gain': '10–14 dBi',
      'Impedance': '50 Ohm',
      'Base Weight': '600g',
    }
  },
  {
    id: 'yagi-elite',
    slug: 'yagi-elite',
    name: 'Yagi Elite',
    tagline: 'Maximum Range, Maximum Power',
    description: `The Yagi Elite is our premium long-range antenna for extreme signal conditions. With a 15M cable, it's ideal for remote areas, rooftop installations, or situations where the router must be placed far from the mounting point. Features superior gain for the weakest signal environments.`,
    badge: 'Premium',
    badgeColor: '#D44F0A',
    warranty: { checking: '5 Days', service: '6 Months' },
    features: [
      'Maximum range for remote areas',
      '15M RG6 low-loss cable included',
      'Universal SMA Male connector (Gold)',
      'Higher gain for extreme signal conditions',
      'Heavy-duty outdoor mounting hardware',
      'Weatherproof all-season design',
    ],
    compatible: ['Dialog 4G Router', 'Mobitel 4G Router', 'SLT 4G Router', 'Hutch 4G Router'],
    variants: [
      {
        id: 'yagi-elite-v1',
        name: '15M Wire + Antenna',
        includes: ['15M RG6 Cable', 'Yagi Elite Antenna Assembly', 'SMA Male Connector (Gold)', 'Heavy-Duty Mounting Hardware'],
        price: 4100,
        weight: 850,
        inStock: true,
      },
      {
        id: 'yagi-elite-v2',
        name: '15M Wire + Antenna + Dipole Weather Protection',
        includes: ['15M RG6 Cable', 'Yagi Elite Antenna Assembly', 'SMA Male Connector (Gold)', 'Dipole Weather Protection Cover', 'Heavy-Duty Mounting Hardware'],
        price: 4300,
        weight: 855,
        inStock: true,
      },
      {
        id: 'yagi-elite-v3',
        name: '15M Wire + Antenna + Director Element Caps',
        includes: ['15M RG6 Cable', 'Yagi Elite Antenna Assembly', 'SMA Male Connector (Gold)', 'Director Element Caps', 'Heavy-Duty Mounting Hardware'],
        price: 4300,
        weight: 870,
        inStock: true,
      },
      {
        id: 'yagi-elite-v4',
        name: '15M Wire + Antenna + Director Caps + Dipole Protection',
        includes: ['15M RG6 Cable', 'Yagi Elite Antenna Assembly', 'SMA Male Connector (Gold)', 'Director Element Caps', 'Dipole Weather Protection Cover', 'Heavy-Duty Mounting Hardware'],
        price: 4500,
        weight: 880,
        inStock: true,
      },
    ],
    images: ['/products/yagi-elite-1.jpg'],
    specs: {
      'Cable Length': '15 Metres',
      'Connector Type': 'SMA Male (Gold Plated)',
      'Cable Type': 'RG6 Low-Loss',
      'Frequency': '700MHz – 2700MHz',
      'Gain': '12–16 dBi',
      'Impedance': '50 Ohm',
      'Base Weight': '850g',
    }
  }
]

export const spareProducts = [
  { id: 'sp-01', slug: 'rg6-cable-10m',            name: 'RG6 Low-Loss Cable (10M)',        category: 'Cable',      price: 650,  weight: 300, description: 'High-quality RG6 low-loss coaxial cable, 10 metres.' },
  { id: 'sp-02', slug: 'rg6-cable-15m',            name: 'RG6 Low-Loss Cable (15M)',        category: 'Cable',      price: 900,  weight: 420, description: 'High-quality RG6 low-loss coaxial cable, 15 metres.' },
  { id: 'sp-03', slug: 'glue-stick-10pcs',          name: 'Glue Stick 10 Pcs',              category: 'Accessory',  price: 120,  weight: 80,  description: 'Standard hot glue sticks, pack of 10.' },
  { id: 'sp-04', slug: 'aluminum-box-bar',          name: 'Aluminum Box Bar 1.7 Feet',       category: 'Structure',  price: 280,  weight: 200, description: 'Aluminum box bar for antenna boom construction.' },
  { id: 'sp-05', slug: 'director-elements',         name: 'Director Elements',               category: 'Element',    price: 150,  weight: 60,  description: 'Aluminum director elements for Yagi antenna.' },
  { id: 'sp-06', slug: 'reflector-elements',        name: 'Reflector Elements',              category: 'Element',    price: 150,  weight: 80,  description: 'Aluminum reflector elements for Yagi antenna.' },
  { id: 'sp-07', slug: 'driven-element-kit',        name: 'Driven Element Kit',              category: 'Element',    price: 350,  weight: 120, description: 'Complete driven element kit with dipole assembly.' },
  { id: 'sp-08', slug: 'u-bolt-type-b',             name: 'U-Bolt Type B',                   category: 'Hardware',   price: 300,   weight: 50,  description: 'Heavy-duty U-bolt for pole mounting, Type B.' },
  { id: 'sp-09', slug: 'u-bolt-type-a',             name: 'U-Bolt Type A',                   category: 'Hardware',   price: 270,   weight: 35,  description: 'Standard U-bolt for pole mounting, Type A.' },
  { id: 'sp-10', slug: 'round-end-caps',            name: 'Round End Caps',                  category: 'Cap',        price: 50,   weight: 20,  description: 'PVC round end caps for element protection.' },
  { id: 'sp-11', slug: 'f-male-connector',          name: 'F Male Connector',                category: 'Connector',  price: 60,   weight: 15,  description: 'F-type male connector for RG6 cable termination.' },
  { id: 'sp-12', slug: 'f-female-connector',        name: 'F Female Connector',              category: 'Connector',  price: 60,   weight: 15,  description: 'F-type female coupler/connector.' },
  { id: 'sp-13', slug: 'reverts',                   name: 'Reverts',                         category: 'Hardware',   price: 40,   weight: 20,  description: 'Aluminum rivets for element attachment.' },
  { id: 'sp-14', slug: 'square-top-round-end-caps', name: 'Square Top Round End Caps',       category: 'Cap',        price: 60,   weight: 25,  description: 'Square-top round end caps for boom ends.' },
  { id: 'sp-15', slug: 'cable-tie-8inch',           name: 'Cable Tie 8 Inches',              category: 'Accessory',  price: 30,   weight: 15,  description: 'Heavy-duty nylon cable ties, 8 inches.' },
  { id: 'sp-16', slug: 'cable-tie-4inch',           name: 'Cable Tie 4 Inches',              category: 'Accessory',  price: 25,   weight: 10,  description: 'Standard nylon cable ties, 4 inches.' },
  { id: 'sp-17', slug: 'heat-shrink-8mm',           name: 'Heat Shrink Tube 8MM',            category: 'Accessory',  price: 80,   weight: 30,  description: '8MM diameter heat shrink tubing for cable protection.' },
  { id: 'sp-18', slug: 'celo-tape',                 name: 'Celo Tape',                       category: 'Accessory',  price: 45,   weight: 50,  description: 'Clear adhesive tape for cable securing.' },
  { id: 'sp-19', slug: 'dipole-box',                name: 'Dipole Box',                      category: 'Element',    price: 60,  weight: 16,  description: 'Weatherproof dipole housing box.' },
  { id: 'sp-20', slug: '3mm-drill-bits',            name: '3MM Drill Bits',                  category: 'Tool',       price: 120,  weight: 30,  description: '3MM HSS drill bits for antenna construction.' },
  { id: 'sp-21', slug: '6-inch-bolt',               name: '6" Bolt',                         category: 'Hardware',   price: 35,   weight: 25,  description: '6-inch stainless steel bolt for mounting.' },
  { id: 'sp-22', slug: '10mm-nuts-silver',          name: '10mm Nuts (Silver Plated)',        category: 'Hardware',   price: 25,   weight: 10,  description: '10mm silver-plated nuts for antenna assembly.' },
  { id: 'sp-23', slug: '95mm-pvc-end-cup',          name: '95mm PVC End Cup',                category: 'Cap',        price: 90,   weight: 45,  description: '95mm PVC end cup for weatherproofing.' },
  { id: 'sp-24', slug: 'aluminum-flat-bar',         name: 'Aluminum 1/2" Flat Bar',          category: 'Structure',  price: 180,  weight: 150, description: 'Half-inch aluminum flat bar for custom mounts.' },
  { id: 'sp-25', slug: 'sma-male-connector-gold',   name: 'SMA Male Connector (Gold)',       category: 'Connector',  price: 180,  weight: 20,  description: 'Gold-plated SMA male connector for router connection.' },
]

export const testimonials = [
  { id: 1, name: 'Kumaran S.', location: 'Vavuniya', rating: 5, text: 'Excellent product! My Dialog 4G signal went from 1 bar to full 4 bars. Download speed increased from 2Mbps to 18Mbps. Worth every rupee.', hasScreenshot: false },
  { id: 2, name: 'Priya N.', location: 'Ampara', rating: 5, text: 'I live in a remote area and had almost no internet. After installing Yagi Elite, my Mobitel router works perfectly. The team was very helpful with installation guidance.', hasScreenshot: false },
  { id: 3, name: 'Rajan T.', location: 'Trincomalee', rating: 5, text: 'Fast delivery to Trinco. The antenna boosted my SLT signal significantly. The 15M cable was perfect for my rooftop installation.', hasScreenshot: false },
  { id: 4, name: 'Anitha K.', location: 'Badulla', rating: 5, text: 'My village has very weak signal. After this antenna, my students can attend online classes without interruption. Thank you Techo Connect!', hasScreenshot: false },
  { id: 5, name: 'Selvam R.', location: 'Monaragala', rating: 4, text: 'Good quality product. Signal improved a lot. Delivery was quick and the installation guide was easy to follow. Recommended!', hasScreenshot: false },
  { id: 6, name: 'Thilaga M.', location: 'Mullaitivu', rating: 5, text: 'I was skeptical at first but after installing the Yagi Pro, my Hutch 4G router is now giving 15+ Mbps consistently. Amazing difference!', hasScreenshot: false },
]

export const jobOpenings = [
  {
    slug: 'yagi-antenna-technician',
    title: 'Yagi Antenna Technician',
    type: 'Part Time',
    department: 'Field Operations',
    locations: ['Colombo', 'Galle', 'Ampara', 'Ratnapura', 'Kandy', 'Nuwara Eliya', 'Anuradhapura', 'Puttalam', 'Vavuniya', 'Trincomalee', 'Monaragala', 'Badulla', 'Hatton'],
    vacancies: '1–2 per location',
    description: `We are looking for skilled antenna technicians across Sri Lanka to join the Techo Connect field operations team. As a Yagi Antenna Technician, you will be responsible for on-site installation, alignment, and testing of our Yagi antenna products for customers in your region. This is a part-time role with flexible hours, paid per installation.`,
    responsibilities: [
      'Install Yagi antennas at customer premises',
      'Align and optimise antenna direction for maximum signal',
      'Connect antenna cables to wireless routers',
      'Test and verify signal improvement after installation',
      'Provide basic troubleshooting support to customers',
      'Report installation status via WhatsApp to the team',
    ],
    requirements: [
      'Minimum 1 year experience with dish antenna or Yagi antenna installation',
      'Ability to work independently without supervision',
      'Basic understanding of 4G LTE signal principles',
      'Ability to climb and work safely at height (pole mounting)',
      'Own transport preferred (for customer visits)',
      'Good communication skills in local language',
    ],
    benefits: [
      'Paid per installation (competitive rate)',
      'Flexible part-time hours',
      'Training provided on Techo Connect products',
      'Direct WhatsApp support from technical team',
    ],
    active: true,
  }
]
